GET http://localhost:3000/users

###

GET http://localhost:3000/users/7KfCCD-0L

###

POST http://localhost:3000/auth
content-type: application/json

{
  "password": "12345",
  "email": "jeanpierm@email.com"
}

###

POST http://localhost:3000/users
content-type: application/json

{
  "email": "jeanpierm@email.com",
  "password": "12345",
  "firstName": "Luis",
  "lastName": "Mendoza"
}

###

POST http://localhost:3000/users
content-type: application/json

{
  "password": "123",
  "email": "jeanpiermendoza@outlook.com"
}

###

PUT http://localhost:3000/users/xIg421jbn
content-type: application/json

{
  "email": "ronaldo@email.com",
  "password": "1234",
  "firstName": "Ronaldo",
  "lastName": "Gualpa"
}

###

PATCH http://localhost:3000/users/ZxfguJjvD
content-type: application/json

{
  "firstName": "Jeanpier",
  "lastName": "Mendoza"
}

###

DELETE http://localhost:3000/users/ZxfguJjvD

###
