GET http://localhost:3000/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3S2ZDQ0QtMEwiLCJlbWFpbCI6ImplYW5waWVyQGVtYWlsLmNvbSIsInBlcm1pc3Npb25GbGFncyI6OCwicmVmcmVzaEtleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6WzY5LDExMSwxODMsMjIzLDEzLDIzMSwyMjAsMjM0LDE0LDE2MCw3NiwxLDIyNSw4NiwxNzQsODddfSwiaWF0IjoxNjI0MTY1MjcyLCJleHAiOjE2MjQyMDEyNzJ9.tA9bJTzoLTz_wW9q9uJn32ophjFVYHApvki2gVitIVw

###

GET http://localhost:3000/users/IBcYOjFzV
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJJQmNZT2pGelYiLCJlbWFpbCI6ImplYW5waWVybUBlbWFpbC5jb20iLCJwZXJtaXNzaW9uRmxhZ3MiOjEsInJlZnJlc2hLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOlsxNCwyMzYsMjUyLDE0MSwyNTEsMTE1LDc4LDY0LDIxNSwxMiw3MCw4NiwxMDksMTE4LDE5NSwxNzJdfSwiaWF0IjoxNjIzNzAxODgwLCJleHAiOjE2MjM3Mzc4ODB9.wdX6eknXVwUpKPMLqZp-07AS8JTg8_L04QHcGrChxuA

###

POST http://localhost:3000/auth
content-type: application/json

{
  "password": "12345",
  "email": "jeanpier@email.com"
}

###

POST http://localhost:3000/auth/refresh-token
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJJQmNZT2pGelYiLCJlbWFpbCI6ImplYW5waWVybUBlbWFpbC5jb20iLCJwZXJtaXNzaW9uRmxhZ3MiOjEsInJlZnJlc2hLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOlsyMDAsMTA0LDk2LDIxMiwxNTMsNDcsMjQ3LDI0MSw1OSwyNTIsMjQxLDE2Miw1NiwzNCwxMzUsODVdfSwiaWF0IjoxNjIzNDM5NTAwLCJleHAiOjE2MjM0NzU1MDB9.uznWY9LQzwxY-AoPWBpgSZqQGoZdBDB731QHQotJ3oM

{
  "refreshToken": "Sgk4INQFpz2qt5AO4hLv2pAgxjUzN3+vjcId+Ho6fAjeL7NF0Ufgtf0BbtopSEXsluvgiZKK3yQ+0NzC/aOOJw=="
}

###

POST http://localhost:3000/users
content-type: application/json

{
  "email": "jeanpierm@email.com",
  "password": "12345",
  "firstName": "Luis",
  "lastName": "Mendoza"
}

###

POST http://localhost:3000/users
content-type: application/json

{
  "password": "123",
  "email": "jeanpiermendoza@outlook.com"
}

###

PUT http://localhost:3000/users/IBcYOjFzV
content-type: application/json

{
  "email": "ronaldo@email.com",
  "password": "1234",
  "firstName": "Ronaldo",
  "lastName": "Gualpa"
}

###

PATCH http://localhost:3000/users/IBcYOjFzV
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJJQmNZT2pGelYiLCJlbWFpbCI6ImplYW5waWVybUBlbWFpbC5jb20iLCJwZXJtaXNzaW9uRmxhZ3MiOjIxNDc0ODM2NDcsInJlZnJlc2hLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOls1NCw5MCwyMzQsNTgsMTY3LDE1MCw2Nyw3MywxODEsMjM0LDUzLDEsMjEwLDU2LDIzMiwxNzNdfSwiaWF0IjoxNjIzNzAyMTE1LCJleHAiOjE2MjM3MzgxMTV9.cdSZLPtjFKMqgeueJm__lmb8zEsqL3AwRmp-sG42rx8

{
  "firstName": "Jeanpier",
  "lastName": "Mendoza"
}

###

DELETE http://localhost:3000/users/ZxfguJjvD

###
