GET http://localhost:3000/users

###

GET http://localhost:3000/users/lPMz7-QlJ

###

POST http://localhost:3000/users
content-type: application/json

{
  "email": "ronaldo@email.com",
  "password": "123",
  "firstName": "Ronaldo",
  "lastName": "Gualpa",
  "permissionLevel": 1,
  "extra": "extra"
}

###

PUT http://localhost:3000/users/lPMz7-QlJ
content-type: application/json

{
  "email": "ronaldo@email.com",
  "password": "123",
  "firstName": "Ronaldo",
  "lastName": "Gualpa"
}

###

PATCH http://localhost:3000/users/lPMz7-QlJ
content-type: application/json

{
  "firstName": "Guido"
}

###

DELETE http://localhost:3000/users/lPMz7-QlJ

###
